### ISSUE TITLE
afterRecipes cannot be triggered

### ISSUE THREAD

**Issue by Gu-meng** [KubeJS-Mods/KubeJS#849] opened 2024-06-11 19:03 UTC
### Minecraft Version

1.20.1

### KubeJS Version

kubejs-forge-2001.6.5-build.7

### Rhino Version

rhino-forge-2001.2.2-build.18

### Architectury Version

architectury-9.2.14-forge

### Forge/Fabric Version

forge 47.2.32

### Describe your issue

```javascript
ServerEvents.afterRecipes(event =>{
    console.log("afterRecipes");
});
``` 
When I wrote this down and didn't see it in the log, I wondered if it didn't trigger

**Comment by ChiefArug** [comment] 2024-06-11 23:59
Duplicate of #327

**Closed by ChiefArug** 2024-06-11 23:59 UTC
Labels: bug
