### ISSUE TITLE
[Crash - Fabric] KubeJS + Voxel Map Crash without showing neither mods in logs...

### ISSUE THREAD

**Issue by TBiscuit1** [KubeJS-Mods/KubeJS#96] opened 2021-03-16 15:35 UTC
Somehow, KubeJS Fabric and Voxel Map Crash Together...
The thing is, there is no mention of either mods in the logs
This bug is REALLY obscure
And yes, when either mod is loaded alone, they work like if nothing happened...
wth

[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/6150205/latest.log)

https://github.com/KubeJS-Mods/KubeJS/issues/81
Here is the issue that made me realised that both mod crash together

**Comment by MaxNeedsSnacks** [comment] 2021-03-16 15:48
Duplicate of https://github.com/architectury/architectury-api/issues/35

**Closed by MaxNeedsSnacks** 2021-03-16 15:48 UTC
