### ISSUE TITLE
Custom recipe ingredients are stripped of NBT

### ISSUE THREAD

**Issue by aaronhowser1** [KubeJS-Mods/KubeJS#588] opened 2023-02-22 03:12 UTC
### Minecraft Version

1.19.2

### KubeJS Version

kubejs-forge-1902.6.0-build.135

### Rhino Version

rhino-forge-1902.2.2-build.264

### Architectury Version

architectury-6.5.69-forge

### Forge/Fabric Version

Forge 43.2.4

### Describe your issue

```js
ServerEvents.recipes(recipe => {

	recipe.remove({output: 'enderstorage:ender_chest'})
	recipe.shaped('enderstorage:ender_chest',[
		' H ',
		' P ',
		' C '
	],{
		P: 'enderstorage:ender_pouch',
		C: 'minecraft:ender_chest',
		H: Item.of('hostilenetworks:prediction', '{data_model:{id:"hostilenetworks:enderman"}}')
	}).stage('enderchest')

})
```
![image](https://user-images.githubusercontent.com/15698722/220511623-c8f87b46-6107-41bf-825c-90e7038fa911.png)

I thought this was the other mod's fault (Shadows-of-Fire/Hostile-Neural-Networks/issues/28) and made myself look like a FOOL

![image](https://user-images.githubusercontent.com/15698722/220511699-6452d02b-2d1f-4ce0-9440-e8d55ebadc03.png)
Swapping it out for another random item with NBT, that one's also broken. Looks like NBT is just stripped straight off the item.
![image](https://user-images.githubusercontent.com/15698722/220511777-21e64f4b-f715-4a5c-8ddd-863b48868d40.png)

**Comment by ChiefArug** [comment] 2023-02-22 03:21
You need to add .weakNBT() after it, as all ingredient are ignoreNBT() by default in 1.19

**Comment by aaronhowser1** [comment] 2023-02-22 03:22
Do I add this after .shaped() and before .stage() ?

**Comment by ChiefArug** [comment] 2023-02-22 03:22
its per ingredient

**Comment by ChiefArug** [comment] 2023-02-22 03:25
Duplicate of #579

**Closed by ChiefArug** 2023-02-22 03:25 UTC
Labels: bug
