### ISSUE TITLE
Fabric 1.18 infinite load.

### ISSUE THREAD

**Issue by ChubbsWasTaken** [KubeJS-Mods/KubeJS#237] opened 2021-12-11 16:39 UTC
Infinite load error when starting with KubeJS for Fabric installed.

Error: Start CurseForge 1.18 modpack for Fabric, Load. bug out and reload everything causing an infinite load loop.

Minecraft version: 1.18
Fabric Version: 0.12.8
Mod Version: kubejs-fabric-1800.4.0-build.235.jar

Modlist: https://pastebin.com/jmU2PDiA (does not contain KubeJS)

**Comment by MJRamon** [comment] 2021-12-17 03:04
Same problem. Infinite Mojang logo loop.

This one loops over and over: https://pastebin.com/PBiPLjtP

**Comment by MJRamon** [comment] 2021-12-18 22:57
I have to stress out this problem, as it makes KubeJS unusable for 1.18.1.

**Comment by MaxNeedsSnacks** [comment] 2021-12-19 01:50
I'm unfortunately suspecting that this is caused by Inspecio, and thus cannot be fixed on our end. Can you see whether the issue persists without it?

**Comment by MJRamon** [comment] 2021-12-19 02:55
Removing Inspecio did indeed fixed the problem and KubeJS started to work.

**Comment by LemmaEOF** [comment] 2021-12-19 04:22
What the hell?

**Comment by LemmaEOF** [comment] 2021-12-19 04:27
It's because of the KubeJS hook on TagLoader, it looks. [Here's](https://github.com/Queerbric/Inspecio/blob/1.17/src/main/java/io/github/queerbric/inspecio/resource/InspecioResourceReloader.java#L51) the crashing line, This is necessary and unavoidable so that tags can be used client-side. If you put in a null-check for the script manager, it won't cause this crash.

**Closed** 2021-12-20 12:54 UTC
