### ISSUE TITLE
Tooltip issue with nbt

### ISSUE THREAD

**Issue by OfficialZygorg** [KubeJS-Mods/KubeJS#276] opened 2022-01-28 15:12 UTC
Custom Machinery mod, to add recipes with kubejs requires an nbt tag.

`tooltip(Item.of('custommachinery:custom_machine_item',{machine:'custommachinery:basic_refiner'}),[
       'A machine to simply melt down cobblestone via unknown means.',
       '§4§lWARNING: DONT DRINK THE UNREFINED COBBLESTONE'])`

The nbt tag is `{machine:'custommachinery:basic_refiner'}`, but because the item id is always `custommachinery:custom_machine_item` it applies the tooltip to every custom machine

Example:

![unknown](https://user-images.githubusercontent.com/43007952/151571420-a07f40da-d01c-4999-a9ff-5ed616a7e3b5.png)
![unknown](https://user-images.githubusercontent.com/43007952/151571438-c8cbb6a7-387f-4bd2-a439-7018a3f8c488.png)

**Comment by Spiker985** [comment] 2022-01-29 09:16
Duplicate of #210

**Closed by Spiker985** 2022-01-29 09:16 UTC
