### ISSUE TITLE
die Loaded common.properties

### ISSUE THREAD

**Issue by xibaoning** [KubeJS-Mods/KubeJS#443] opened 2022-08-05 09:44 UTC
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.4-build.533

### Rhino Version

rhino-fabric-1802.1.14-build.206

### Architectury Version

architectury-4.7.78-fabric

### Forge/Fabric Version

fabric-api-0.58.0+1.18.2

### Describe your issue

E:\Game\server>"C:\Program Files\Java\jdk-18.0.2\bin\java.exe" -Xmx8000M -Xms1024M -jar fabric-server-launch.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:41:09] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.8
[17:41:09] [main/INFO]: Loading 40 mods:
        - architectury 4.7.78
        - fabric 0.58.0+1.18.2
        - fabric-api-base 0.4.4+d7c144a860 via fabric
        - fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
        - fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
        - fabric-command-api-v1 1.1.9+d7c144a860 via fabric
        - fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
        - fabric-containers-v0 0.1.23+d7c144a860 via fabric
        - fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
        - fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
        - fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
        - fabric-data-generation-api-v1 3.0.1+9fcb91d260 via fabric
        - fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
        - fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
        - fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
        - fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric
        - fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
        - fabric-item-api-v1 1.5.2+17cbbd4360 via fabric
        - fabric-item-groups-v0 0.3.14+91896a4960 via fabric
        - fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
        - fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
        - fabric-loot-tables-v1 1.1.2+e747827960 via fabric
        - fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
        - fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric
        - fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric
        - fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
        - fabric-particles-v1 0.2.12+526dc1ac60 via fabric
        - fabric-registry-sync-v0 0.9.10+0d9ab37260 via fabric
        - fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
        - fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
        - fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
        - fabric-resource-loader-v0 0.5.2+446e059560 via fabric
        - fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric
        - fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
        - fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
        - fabricloader 0.14.8
        - java 18
        - kubejs 1802.5.4-build.533
        - minecraft 1.18.2
        - rhino 1802.1.14-build.206
[17:41:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/E:/Game/server/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:41:10] [main/INFO]: Compatibility level set to JAVA_16
[17:41:10] [main/INFO]: Compatibility level set to JAVA_17
[17:41:20] [main/INFO]: Looking for KubeJS plugins...
[17:41:20] [main/INFO]: Found plugin source kubejs
[17:41:20] [main/INFO]: Done in 184.6 ms
[17:41:20] [main/INFO]: Loaded common.properties

**Comment by ChiefArug** [comment] 2022-08-05 09:46
Duplicate of https://github.com/KubeJS-Mods/KubeJS/issues/427

**Closed** 2022-08-05 09:46 UTC
Labels: bug
