### ISSUE TITLE
Eating food causes server to crash

### ISSUE THREAD

**Issue by MoshiBar** [KubeJS-Mods/KubeJS#171] opened 2021-07-31 23:15 UTC
here is the crash report
[crash-2021-07-31_19.11.51-server.txt](https://github.com/KubeJS-Mods/KubeJS/files/6911929/crash-2021-07-31_19.11.51-server.txt)

**Comment by Spiker985** [comment] 2021-07-31 23:21
@MoshiBar
Please provide as much information as possible about what you were doing when this crash happened.

Do you have any KubeJS scripting in use. If so, please attach.

Was this caused by a custom item? See previous question.

Do you have a latest.log, and debug.log? If so, please attach.

**Comment by chopspry** [comment] 2021-07-31 23:24
### I had the same issue, crash log however was empty, tested it twice. I was eating bread after updating all of the kubejs mods and create, and also updating to the newest forge version to accommodate the create update.
[09:10:54] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$20245/1073762033.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at dev.latvian.kubejs.core.LivingEntityKJS.foodEatenKJS(LivingEntityKJS.java:23) ~[?:1605.3.13-build.52]
	at net.minecraft.entity.LivingEntity.handler$zjb000$foodEaten(LivingEntity.java:8450) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_213357_a(LivingEntity.java) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_213357_a(PlayerEntity.java:1978) ~[?:?]
	at net.minecraft.item.Item.func_77654_b(Item.java:124) ~[?:?]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:221) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1057) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	... 7 more

**Comment by LatvianModder** [comment] 2021-07-31 23:45
Fixed in latest update

**Closed** 2021-08-19 11:06 UTC
