### ISSUE TITLE
item.tooltip not working

### ISSUE THREAD

**Issue by red2blue** [KubeJS-Mods/KubeJS#196] opened 2021-09-20 17:38 UTC
MC 1.17.1
Fabric
Latest KubeJS

I tried using item.tooltip like how you used it in your wiki in Server_side, Client_side, and startup, and it doesn't work. 

`[19:34:17] [ERR ] Error occurred while handling event 'item.tooltip': Can't find method dev.latvian.kubejs.item.ItemTooltipEventJS.add(string,object,object). (client_scripts:tooltip.js#5)`
```

onEvent('item.tooltip', tooltip => {

   tooltip.add('carrier:glove', ["Carry and move any block with a storage", "Line 1"], [text.red('Sneak + Right Click') + ' on block', 'Line 2']);
 });
```

Not working =/

**Comment by Spiker985** [comment] 2021-09-20 19:04
The 1.17 version is unsupported as listed on the download page in CurseForge. 

However, this might be fixed by using `items.tooltip` instead of `item`

**Comment by MaxNeedsSnacks** [comment] 2021-09-20 19:06
The issue is actually more that they're using multiple arrays as the parameter, it should just be

```js
onEvent('item.tooltip', tooltip => {
   tooltip.add('carrier:glove', ["Carry and move any block with a storage", text.red('Sneak + Right Click') + ' on block']);
});
```

**Closed** 2021-09-20 19:06 UTC
Labels: invalid, unsupported
