### ISSUE TITLE
Adding this mod appears to immediately break fluid recipes using alternate containers

### ISSUE THREAD

**Issue by MuteTiefling** [KubeJS-Mods/KubeJS#14] opened 2020-06-30 03:32 UTC
Version: kubejs-2.7.0.41.jar

https://github.com/NillerMedDild/Enigmatica5/issues/387

PneumaticCraft introduced a tank in 1.15 that can be used in place of buckets for batch fluid crafting. Similarly Immersive Engineering has it's Jerry Can which serves the same function. 

Both of these stop working as soon as KubeJS is installed. The recipe for Treated Wood, for instance, only works with buckets. The recipe for PNC's Speed Upgrades only works with buckets of lubricant. Removing KubeJS resolves the issue and allows both crafts to work normally with buckets, jerry cans, and pnc tanks

**Comment by MuteTiefling** [comment] 2020-06-30 03:33
Logs : [2020-06-29-1.log.gz](https://github.com/KubeJS-Mods/KubeJS/files/4849304/2020-06-29-1.log.gz)

**Comment by LatvianModder** [comment] 2020-07-01 10:44
I see what the problem is, it's using entirely custom ingredient:

```
{
  "amount": 1000,
  "fluid": "immersiveengineering:creosote",
  "type": "immersiveengineering:fluid"
}
```

I'll see if I can get this fixed asap

**Comment by LatvianModder** [comment] 2020-07-02 13:04
Should be fixed in https://jenkins.latmod.com/job/KubeJS-1.15/1/

**Closed by LatvianModder** 2020-07-02 13:04 UTC
