### ISSUE TITLE
Crash with Create Fabric when placing a Basin

### ISSUE THREAD

**Issue by skippyall** [KubeJS-Mods/KubeJS#697] opened 2023-09-06 14:11 UTC
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.3-build.23

### Rhino Version

2001.2.2-build.6

### Architectury Version

9.1.12

### Forge/Fabric Version

0.14.22

### Describe your issue

When placing down a Basin from the Create mod (0.5.1-d-build.1161+mc1.20.1), the game crashes with this report.
[crash-2023-09-06_16.04.17-client.txt](https://github.com/KubeJS-Mods/KubeJS/files/12538704/crash-2023-09-06_16.04.17-client.txt)
This does not occur without KubeJS

**Comment by MaxNeedsSnacks** [comment] 2023-09-06 14:17
I don't see how this issue is related to KubeJS.

**Comment by MaxNeedsSnacks** [comment] 2023-09-06 14:21
I think this is caused by a version difference in Fabric API, if anything. If that's outdated, try updating it

**Comment by skippyall** [comment] 2023-09-06 14:28
Fabric API version is 0.88.1+1.20.1 (The newest for 1.20.1)

**Comment by skippyall** [comment] 2023-09-08 08:12
I got an other crash report in my modpack where this issue first occured to me. Maybwe this is more helpful (although this can't be well reproduced)
[crash-2023-09-08_09.48.35-server.txt](https://github.com/KubeJS-Mods/KubeJS/files/12557113/crash-2023-09-08_09.48.35-server.txt)

**Comment by ChiefArug** [comment] 2023-09-09 13:07
This was [discussed](https://discord.com/channels/303440391124942858/303440391124942858/1149645420939706369) on [Discord](https://discord.gg/lat), turns out it was KubeJS causing the problem. Also see the mentioned issue above on Create's tracker.

This is now fixed in 17d5278fd4d5a6c2c03b7f375b4a1563c26e5b9a

**Closed by ChiefArug** 2023-09-09 13:07 UTC
Labels: bug
