### ISSUE TITLE
Right clicking with item stack in creative causes CTD

### ISSUE THREAD

**Issue by ZeburaBlack** [KubeJS-Mods/KubeJS#93] opened 2021-03-14 02:39 UTC
[21:37:23] [main/ERROR]: An uncaught exception occured while displaying the crash screen, making normal report instead
java.lang.NullPointerException: null
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5) ~[?:?]
	at dev.latvian.kubejs.entity.EntityEventJS.entityOf(EntityEventJS.java:22) ~[kubejs-1605.3.6-build.175-fabric.jar:?]
	at dev.latvian.kubejs.item.ItemTossEventJS.getEntity(ItemTossEventJS.java:27) ~[kubejs-1605.3.6-build.175-fabric.jar:?]
	at dev.latvian.kubejs.entity.EntityEventJS.getWorld(EntityEventJS.java:17) ~[kubejs-1605.3.6-build.175-fabric.jar:?]
	at dev.latvian.kubejs.world.WorldEventJS.post(WorldEventJS.java:30) ~[kubejs-1605.3.6-build.175-fabric.jar:?]
	at dev.latvian.kubejs.item.KubeJSItemEventHandler.drop(KubeJSItemEventHandler.java:96) ~[kubejs-1605.3.6-build.175-fabric.jar:?]
	at dev.latvian.kubejs.item.KubeJSItemEventHandler$$Lambda$2392/802032064.drop(Unknown Source) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.handler$zjf000$drop(PlayerEntity:4343) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.dropItem(PlayerEntity:752) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.dropItem(PlayerEntity:706) ~[?:?]
	at net.minecraft.screen.ScreenHandler.close(ScreenHandler:457) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.removed(HandledScreen:609) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.removed(CreativeInventoryScreen:361) ~[?:?]
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient:896) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.displayCrashScreen(InGameCatcher.java:73) ~[notenoughcrashes-3.1.7-fabric.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35) ~[notenoughcrashes-3.1.7-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.modify$cfb000$onCrash(MinecraftClient:10912) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:699) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]

**Comment by MaxNeedsSnacks** [comment] 2021-03-14 19:40
May be related / duplicate of #79

**Comment by MaxNeedsSnacks** [comment] 2021-03-15 13:52
May I ask, what item did you right click for things to crash?

**Comment by MaxNeedsSnacks** [comment] 2021-03-15 14:19
Should be fixed in the latest build

**Closed by MaxNeedsSnacks** 2021-03-15 14:19 UTC
Labels: bug
