### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by windy664** [KubeJS-Mods/KubeJS#684] opened 2023-08-08 07:02 UTC
### Describe the feature

I would like to request that KubeJS be updated to support 1.20. This will allow users to take advantage of the latest features and improvements introduced in this version.

### Additional info

Many users, including myself, have been eagerly waiting for this update and believe it would greatly enhance the user experience.With the increasing popularity of version 1.20, it's essential to keep KubeJS compatible and up-to-date with the latest version to ensure its continued success and relevance in the community. While there might be other solutions or workarounds, having native support for 1.20 would offer the most seamless and efficient experience for users.Users could potentially stick with older versions or use patches, but this is not ideal. Native support would be the most straightforward and effective solution.

**Comment by screret** [comment] 2023-08-08 07:03
it'll be done when it'll be done.

**Comment by ChiefArug** [comment] 2023-08-08 07:24
Duplicate of https://github.com/KubeJS-Mods/KubeJS/issues/654

**Closed by ChiefArug** 2023-08-08 07:24 UTC
Labels: enhancement

**Comment by Prunoideae** [comment] 2023-08-08 09:14
We are likely to skip 1.20.1 and upgrade to 1.20.2 instead, due to several technical changes introduced in the recent snapshot.
