### ISSUE TITLE
KubeJS Crash when starting world when adding any worldgen structure_set

### ISSUE THREAD

**Issue by pietro-lopes** [KubeJS-Mods/KubeJS#708] opened 2023-09-23 08:35 UTC
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.3-build.47

### Rhino Version

2001.2.2-build.6

### Architectury Version

9.1.12

### Forge/Fabric Version

Forge 47.1.76

### Describe your issue

how to reproduce:
grab any valid structure_set and add any of those:
* low priority data on server event
* high priority data on server event
* data folder to act as datapack

example below from original minecraft files
```json
{
  "placement": {
    "type": "minecraft:random_spread",
    "salt": 20083232,
    "separation": 8,
    "spacing": 24
  },
  "structures": [
    {
      "structure": "minecraft:ancient_city",
      "weight": 1
    }
  ]
}
```

### Crash report/logs

https://pastebin.com/TfzTQspv

**Comment by ChiefArug** [comment] 2023-09-23 08:36
The root cause seems to be KubeJS returning the resource for both `namespace:worldgen/structure_set/` and `namespace:worldgen/structure/set`, however I cannot find any code in KubeJS that replaces _ with /.

**Comment by pietro-lopes** [comment] 2023-09-23 10:36
also happens to noise_settings

```md
> Errors in registry minecraft:worldgen/noise:
>> Errors in element sgjourney:settings/abydos:
java.lang.IllegalStateException: Failed to parse sgjourney:worldgen/noise_settings/abydos.json from pack KubeJS Resource Pack [data]
```

**Comment by LatvianModder** [comment] 2023-09-28 15:29
Should be fixed in https://github.com/KubeJS-Mods/KubeJS/commit/5ee42ccbd936fe1e67ffd5aeed3805de92769e5b

**Closed by LatvianModder** 2023-09-28 15:29 UTC
Labels: bug
