### ISSUE TITLE
[KubeJS Thermal] Errors in currently selected datapacks prevented the world from loading

### ISSUE THREAD

**Issue by tunaeskanaytac** [KubeJS-Mods/KubeJS#167] opened 2021-07-29 14:11 UTC
(KubeJs and KubeJs Thermal's author was the same person and since KubeJs Thermal didn't have a issues or comments section I figured I should post the issue here)

When I use KubeJS Thermal after the latest thermal updates I neither could load an existing world or create a new world
![image](https://user-images.githubusercontent.com/13142062/127505602-80d8c268-6204-469c-98dd-35de5ff7c88b.png)

here's the log file
https://pastebin.com/K8ZJaUhQ

'Hoping you can help me

**Comment by MaxNeedsSnacks** [comment] 2021-07-29 21:33
Duplicate of https://github.com/KubeJS-Mods/KubeJS-Thermal/issues/3

**Comment by MaxNeedsSnacks** [comment] 2021-07-29 21:34
FWIW, Lat already fixed this, so just update KubeJS Thermal now ^^

**Closed by MaxNeedsSnacks** 2021-07-29 21:33 UTC
