### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by SevenChords** [KubeJS-Mods/KubeJS#628] opened 2023-05-30 10:23 UTC
### Minecraft Version

1.19.4

### KubeJS Version

kubejs-forge-1902.6.0-build.142

### Rhino Version

rhino-forge-1902.2.2-build.268

### Architectury Version

architectury-8.1.87-forge

### Forge/Fabric Version

Forge 45.0.64

### Describe your issue

client crashes during startup, no kubejs scripts have been written or added by me.
some mixin error mentioning backgroundBrightnessKJS

### Crash report/logs

https://mclo.gs/ouABteE

**Comment by ChiefArug** [comment] 2023-05-30 10:24
KubeJS does not work on 1.19.4 yet. It is unkown if it ever will.
1.19.2 is currently the latest supported version.

**Comment by ChiefArug** [comment] 2023-07-21 08:22
Closing as duplicate of #624

**Closed by ChiefArug** 2023-07-21 08:22 UTC
Labels: bug
