### ISSUE TITLE
Catching of exceptions from RecipeComponent#read causes errors from StringComponent#DYNAMIC to be lost to scripters

### ISSUE THREAD

**Issue by ChiefArug** [KubeJS-Mods/KubeJS#753] opened 2023-12-12 02:56 UTC
### Minecraft Version

1.20.1

### KubeJS Version

kubejs-forge-2001.6.4-build.114.jar

### Rhino Version

 rhino-forge-2001.2.2-build.18.jar

### Architectury Version

architectury-9.1.12-forge.jar

### Forge/Fabric Version

47.2.17

### Describe your issue

The try/catch here: https://github.com/KubeJS-Mods/KubeJS/blob/cfa1420e8235ef4cd10474d6ed086ed59c0e9720/common/src/main/java/dev/latvian/mods/kubejs/recipe/component/ComponentValueMap.java#L25-L29 causes errors thrown here: https://github.com/KubeJS-Mods/KubeJS/blob/610720f3230078bf36e9a68810dc086a9d63c6b5/common/src/main/java/dev/latvian/mods/kubejs/recipe/component/StringComponent.java#L88-L94 to be caught and not displayed to the scripter because KubeJS doesnt print inner exceptions to the script logs.
Instead an error like `! example.js#2: Failed to create recipe for type 'eidolon:worktable': Unable to cast 'reagents:string' value 'SBB' to 'string'!` shows up.

Test case (requires [Eidolon: Rebrewed](https://www.curseforge.com/minecraft/mc-mods/eidolon-rebrewed)):

```js
//type: startup
const $RecipeSchema = Java.loadClass('dev.latvian.mods.kubejs.recipe.schema.RecipeSchema')
const $ShapedRecipeSchema = Java.loadClass('dev.latvian.mods.kubejs.recipe.schema.minecraft.ShapedRecipeSchema')

StartupEvents.recipeSchemaRegistry(event => {
    const Components = event.components

    let worktableSchema = new $RecipeSchema(
        $ShapedRecipeSchema.RESULT,
        $ShapedRecipeSchema.PATTERN,
        Components.get('filteredString')
            ({ error: "reagents must have a length of four", filter: s => s.length == 4})
            .key('reagents'),
        $ShapedRecipeSchema.KEY
    )

    event.register('eidolon:worktable', worktableSchema);
})
```

```js
//type: server
ServerEvents.recipes(event => {
    event.recipes.eidolon.worktable('apple', [
        ' R ',
        'RPR',
        ' R '
    ], 'SBB', {
        S: 'wheat_seeds',
        B: 'bone_meal',
        R: 'red_dye',
        P: 'potato'
    });
})
```
The error here is that the reagents string (the SBB in the middle) must be of length four, but it shows up as a 'cannot cast' error, not the custom error message.

**Comment by MaxNeedsSnacks** [comment] 2024-02-03 23:23
Fixed by printing the cause in RecipeExceptionJS as well

**Closed by MaxNeedsSnacks** 2024-02-03 23:23 UTC
Labels: bug
